# shop-service/ docker-compose.yml
services:
  shop:
    image: ssrabw/msa-shop:latest
    container_name: shop-service
    
    ports:
      - "8081:8081"      
    # 중요: 개별 변수 매핑 대신 .env 파일을 통한 환경 변수 통합 주입
    env_file:
      - .env      
    environment:
      # 프로필을 prod로 강제 지정 및 타임존 설정
      - SPRING_PROFILES_ACTIVE=prod
      - TZ=Asia/Seoul
      
    volumes:
      # 호스트 경로 : 컨테이너 내부 경로 매핑 (이미지 데이터 영속성 유지)
      - /home/oksm1003/images/shop:/app/resources/static/images/shop      
    networks:
      - msa-network      
    # 컨테이너 비정상 종료 시 자동 재시작
    restart: always

networks:
  msa-network:
    # CI/CD에서 생성/확인하는 외부 공통 네트워크 사용
    external: true