GET http://localhost/msa/shop/shop/detail/7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIxNiIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzczMzg1NjQ4LCJleHAiOjE3NzMzODkyNDh9.dRgdGpMmSQg9N7I9wJrEVjPkmTHPlZpo9Psbj1tM676XJ1XWCa4fE-S7H6jclUMf