# GET http://34.64.85.123/msa/shop/admin/approval-list
# Content-Type: application/json 
# Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIyMCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc3NDQzMTIzNiwiZXhwIjoxNzc0NDM0ODM2fQ.nHbRWIGzvrsyqLg2Hw0zDREVVoOioSeOHRTF83COdlBp-w8JH3UJUOfJd588F4Tz

GET http://localhost/msa/shop/admin/approval-list
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIyMCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc3NDQzMTIzNiwiZXhwIjoxNzc0NDM0ODM2fQ.nHbRWIGzvrsyqLg2Hw0zDREVVoOioSeOHRTF83COdlBp-w8JH3UJUOfJd588F4Tz

