GET http://34.64.85.123/msa/shop/admin/approval-list
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIyMCIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc3NDQzMzg3MywiZXhwIjoxNzc0NDM3NDczfQ.ooTtMhSabs2BLF2As4B_tbuuBa2GjPTvMKs-aojU9ovC1aeAcpnlqzh6sLpErDcP
