# DB Connection (운영 서버 IP)
spring.datasource.url=jdbc:postgresql://34.50.7.72:5432/msa_shop_db?currentSchema=shop
spring.datasource.username=app_user
spring.datasource.password=user1234 # 실제 운영시에는 암호화 필수

# RabbitMQ (운영 서버 DB와 동일한 Docker 네트워크 내 서비스명 활용)
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=msa_mq
spring.rabbitmq.password=mq1234

# 서버 이미지 저장 경로 (절대 경로 권장)
shop.image.upload-path=/var/www/shop/uploads/images
spring.web.resources.static-locations=file:${shop.image.upload-path}/