# DB Connection (Local 또는 Docker DB)
spring.datasource.url=jdbc:postgresql://34.50.7.72:5432/msa_shop_db?currentSchema=shop
spring.datasource.username=app_user
spring.datasource.password=user1234

# RabbitMQ (Local)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=msa_mq
spring.rabbitmq.password=mq1234

# 로컬 이미지 업로드 경로
shop.image.upload-path=./uploads/images
# /images/** 요청을 처리하기 위해 정적 리소스 위치를 ./uploads/images/로 고정
spring.web.resources.static-locations=file:./uploads/images/