spring.application.name=shop
server.port=8081

# 활성 프로파일 설정 (기본값: dev)
spring.profiles.active=dev
# spring.profiles.active=prod

# 로깅 및 공통 리소스 설정
logging.level.org.springframework.web.servlet.resource=ERROR

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB