# DB Connection (운영 서버 IP)
spring.datasource.url=jdbc:postgresql://34.50.7.72:5432/msa_shop_db?currentSchema=shop
spring.datasource.username=app_user
spring.datasource.password=user1234

# RabbitMQ (운영 서버 DB와 동일한 Docker 네트워크 내 서비스명 활용)
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=msa_mq
spring.rabbitmq.password=mq1234

# 서버 이미지 저장 및 라우팅 경로 (매핑: /images/shop/파일명 -> 위치/파일명)
shop.image.upload-path=/app/resources/static/images/shop
spring.mvc.static-path-pattern=/images/shop/**
spring.web.resources.static-locations=file:${shop.image.upload-path}/